# ----- dependencies -----

[[constraint]]
  name = "github.com/go-redis/redis"
  version = "6.10.2"

[[constraint]]
  name = "github.com/kataras/iris"
  version = "10.6.0"

[prune]
  go-tests = true
  unused-packages = true




# ----- heroku -----

[metadata.heroku]
  root-package = "github.com/stang/go-short"
  go-version = "1.10.1"
  install = ["."]
  ensure = true
 
